server:
  port: 8762
spring:
  application:
    name: eureka
eureka:
  instance:
    nacos
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka,http://consul:8763/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"    