server:
  port: 8763
spring:
  application:
    name: eureka
eureka:
  instance:
    consul
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka,http://nacos:8762/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"   